Delete from [dbo].[SS_MopDetail]

SET IDENTITY_INSERT [dbo].[SS_MopDetail] ON

INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (1, N'Unforeseen contingency requiring immediate purchase/Emergency (with approved Emergency Purchase Certificate) - P100,000 Bellow (''Annex H'')', 0, 100000, 1, 155, N'2017-04-20 15:44:34', 6)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (2, N'off-the shelf goods or ordinary equipment (not available at PS-DBM)', 0, 0, 1, 155, N'2017-04-20 15:44:34', 6)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (3, N'Below PhP 1,000,000 per threshold Annex "H", Revised IRR-A)', 0, 1000000, 1, 155, N'2017-04-20 15:44:34', 6)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (4, N'Will not result in splitting of contracts', 0, 0, 1, 155, N'2017-04-20 15:44:34', 6)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (5, N'Procurement of highly specialized types of goods (e.g., sophisticated defense equipment, complex air navigation systems, coal, etc.)', 0, 0, 1, 1, N'2015-02-17 11:00:42', 2)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (6, N'Major plant components where it is deemed advantageous to limit the bidding to known qualified bidders', 0, 0, 1, 1, N'2015-02-17 11:00:42', 2)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (7, N'Goods can be obtained only from  the proprietary source (patents, copyrights, trade secrets)', 0, 0, 1, 1, N'2015-11-03 11:04:04', 1)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (8, N'Procurement of critical components from a specific mernufacturer, supplier, or distributor is a condition gmdent to hold a contractor to guarantee its project performance', 0, 0, 1, 1, N'2015-11-03 11:04:04', 1)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (9, N'Goods are sold by an exclusive dealer or manufacturer (no sub-deaIers offering lower price AND no suitable  substitute', 0, 0, 1, 1, N'2015-11-03 11:04:04', 1)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (10, N'Two (2) Failed Biddings', 0, 0, 1, 1, N'2015-02-02 18:42:13', 3)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (11, N'Imminent danger to life and/or property; State of Calamity', 0, 0, 1, 1, N'2015-02-02 18:42:13', 3)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (12, N'Take-over of Contracts (rescinded or terminated)', 0, 0, 1, 1, N'2015-02-02 18:42:13', 3)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (13, N'Will be procured through PS-DBM for being classified as  "common supplies and/or office equipment,"', 0, 0, 1, 1, N'2015-02-02 18:42:13', 3)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (14, N'Highly Technical Consultants (6 months tenure only, subject to renewal by HOPE)', 0, 0, 1, 1, N'2015-02-02 18:42:13', 3)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (15, N'Unit prices must be the same as or lower than those in the original contract still the most advantageous after price verification);', 0, 0, 1, 1, N'2015-02-17 11:00:15', 5)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (16, N'Will not result in splitting of contacts, requisitions, or purchased orders', 0, 0, 1, 1, N'2015-02-17 11:00:15', 5)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (17, N'Shall be availed of only within 6 months from the Notice to Proceed;', 0, 0, 1, 1, N'2015-02-17 11:00:15', 5)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (18, N'Shall not exceed twenty-five percent (25% of quantity of each item in the orig. contract', 1, 25, 1, 1, N'2015-02-17 11:00:15', 5)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (19, N'Small Value Procurement', 0, 0, 1, 1, N'2015-02-02 18:42:13', 3)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (20, N'Agency-to-Agency Request', 0, 0, 1, 1, N'2015-02-02 18:42:13', 3)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (21, N'Cash Advance', 0, 0, 1, 1, N'2015-10-13 18:45:05', 7)
INSERT INTO [dbo].[SS_MopDetail] ([MopDetailId], [Description], [IsPercent], [Value], [IsActive], [CreatedByUserId], [CreatedDate], [ModeOfProcurementId]) VALUES (22, N'Petty Cash', 0, 0, 1, 1, N'2015-10-13 18:45:05', 7)

SET IDENTITY_INSERT [dbo].[SS_MopDetail] OFF