

INSERT INTO dbo.Um_Page ([PageId], [PageName], [Description])
VALUES
( 11, N'Role', N'Role' ),
( 12, N'Policy', N'Policy' ),
( 13, N'UserAccount', N'UserAccount' ),
( 14, N'Workflow', N'Workflow' ),
( 15, N'Module', N'Module' ),
( 16, N'FilterCriteria', N'FilterCriteria' ),
( 17, N'ItemType', N'ItemType' ),
( 18, N'Person', N'Person' ),
( 19, N'WorkStep', N'WorkStep' ),
( 20, N'ReferenceTable', N'Reference Table' ),
( 21, N'Supplier', N'Supplier' ),
( 22, N'Section', N'Section' ),
( 23, N'Department', N'Department' ),
( 24, N'Bureau', N'Bureau' ),
( 25, N'UnitOfMeasurement', N'UnitOfMeasurement' ),
( 26, N'DocumentType', N'DocumentType' ),
( 27, N'SubCategory', N'SubCategory' ),
( 28, N'MajorCategory', N'MajorCategory' ),
( 29, N'ItemStatus', N'ItemStatus' ),
( 30, N'ReferenceNumber', N'ReferenceNumber' ),
( 31, N'Accounting', N'Accounting' ),
( 32, N'PSDBMCatalogue', N'PSDBM Catalogue' ),
( 33, N'SupplementaryCatalogue', N'Supplementary Catalogue' ),
( 34, N'ModeOfProcurement', N'ModeOfProcurement' ),
( 35, N'Division', N'Division' ),
( 36, N'PurchasingType', N'PurchasingType' ),
( 37, N'ListOfSignatory', N'ListOfSignatories' ),
( 38, N'SubStatus', N'SubStatus' ),
( 39, N'MopDetails', N'MopDetails' ),
( 40, N'SupplierContactPerson', N'SupplierContactPerson' ),
( 41, N'DataCleanUp', N'DataCleanUp' ),
( 42, N'Bulletin', N'Bulletin' ),
( 43, N'FAQ', N'FAQ' ),
( 44, N'Project', N'Project' ),
( 61, N'PPMP', N'PPMP' ),
( 62, N'APP', N'APP' ),
( 63, N'PR', N'PR' ),
( 64, N'PO', N'PO' ),
( 65, N'Receiving', N'Receiving' ),
( 66, N'WMR', N'WMR' ),
( 68, N'CanvassingRsq', N'CanvassingRSQ' ),
( 69, N'APR', N'AgencyPurchaseRequest' ),
( 70, N'POAdjustments', N'POAdjustments' ),
( 71, N'CanvassingRfq', N'CanvassingRFQ' ),
( 72, N'AbstractOfBids', N'AbstractOfBidding' ),
( 73, N'PPMPAmendment', N'PPMP Amendment' ),
( 74, N'Contract', N'Contract' ),
( 75, N'OtherSupplementary', N'RequestForAdditionalSupplementary' ),
( 81, N'MonitoringSupplies', N'Monitoring Supplies' ),
( 82, N'MonitoringEquipments', N'Monitoring Equipments' ),
( 83, N'ReceivingSupplies', N'ReceivingSupplies' ),
( 84, N'ReceivingEquipments', N'Receiving Equipments' ),
( 85, N'PrItemAuditTrail', N'PR Items Audit Trail' ),
( 86, N'DisposalEquipment', N'Disposal - Equipment' ),
( 87, N'DisposalSupplies', N'Disposal - Supplies' ),
( 88, N'IssuanceEquipment', N'Issuance - Equipment' ),
( 89, N'IssuanceSupplies', N'Issuance - Supplies' ),
( 90, N'BorrowEquipment', N'Borrow - Equipment' ),
( 91, N'ReturnEquipment', N'Return Equipment' ),
( 92, N'TransferEquipment', N'Transfer Equipment' ),
( 93, N'PhysicalCount', N'Physical Count of Inventories' ),
( 101, N'ViewReport', N'View Reports' ),
( 102, N'AccountabilityCheck', N'Accountability Check' ),
( 103, N'MonitoringReports', N'Monitoring Reports' )

