CREATE TABLE [dbo].[PurchaseRequests] (
    [PurchaseRequestId]        INT            IDENTITY (1, 1) NOT NULL,
    [PRNumber]                 NVARCHAR (20)  NULL,
    [RequestingOffice]         INT            NOT NULL,
    [TotalAmount]              DECIMAL (18)   NULL,
    [IsSubmitted]              BIT            NULL,
    [PurchasingType]           SMALLINT       NOT NULL,
    [PpmpId]                   INT            NULL,
    [PpmpNumber]               NVARCHAR (20)  NULL,
    [BudgetYear]               SMALLINT       NOT NULL,
    [Remarks]                  NVARCHAR (MAX) NULL,
    [ModeOfProcurement]        INT            NULL,
    [DatePrepared]             DATETIME       NULL,
    [Purpose]                  NVARCHAR (MAX) NULL,
    [FirstQuarter]             BIT            NULL,
    [SecondQuarter]            BIT            NOT NULL,
    [ThirdQuarter]             BIT            NOT NULL,
    [FourthQuarter]            BIT            NOT NULL,
    [IsRepeatOrder]            BIT            NOT NULL,
    [WithoutPO]                BIT            NOT NULL,
    [IsItemized]               BIT            NOT NULL,
    [Supplier]                 INT            NULL,
    [PRKind]                   INT            NULL,
    [PRClassification]         INT            NULL,
    [IsForDelivery]            BIT            NOT NULL,
    [IsPartialSupply]          BIT            NOT NULL,
    [IsPartialEquipment]       BIT            NOT NULL,
    [HasSupplies]              BIT            NOT NULL,
    [HasEquipments]            BIT            NOT NULL,
    [SubmittedDate]            DATETIME       NULL,
    [SubmittedBy]              INT            NULL,
    [IsConsolidated]           BIT            NOT NULL,
    [IsCreatedBySupplyOfficer] BIT            NOT NULL,
    [ApprovedDate]             DATETIME       NULL,
    [ConsolidatedBy]           INT            NULL,
    [IsActive]                 BIT            NOT NULL,
    [CreatedByUserId]          INT            NOT NULL,
    [CreatedDate]              DATETIME       NOT NULL,
    [UpdatedByUserId]          INT            NULL,
    [UpdatedDate]              DATETIME       NULL,
    [DeletedByUserId]          INT            NULL,
    [DeletedDate]              DATETIME       NULL,
    [IsContract]               BIT            CONSTRAINT [DF_PurchaseRequests_IsContract] DEFAULT ((0)) NOT NULL,
    [ContractId]               INT            NULL,
    [WithCanvassing]           BIT            CONSTRAINT [DF_PurchaseRequests_WithCanvassing] DEFAULT ((0)) NOT NULL,
    [WithApr]                  BIT            CONSTRAINT [DF_PurchaseRequests_WithApr] DEFAULT ((0)) NOT NULL,
    [IsPrSo]                   BIT            NOT NULL,
    [TempPRNumber]             NVARCHAR (100) NULL,
    [OtherRemarks]             NVARCHAR (MAX) NULL,
    [IsForRSQRFQ]              BIT            CONSTRAINT [DF__PurchaseR__IsFor__70D9FCEF] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__Purchase__3602DDBE00E57C2F] PRIMARY KEY CLUSTERED ([PurchaseRequestId] ASC)
);

