CREATE TABLE [dbo].[SS_Signatories] (
    [SignatoryId] [int] IDENTITY(1,1) NOT NULL,
	[Transactions] [int] NULL,
	[Sequence] [int] NULL,
	[SignatoryDesignationId] [int] NULL,
	[SignatoryOfficeId] [int] NULL,
	[ReportSectionId] [int] NULL,
	[WithCondition] [bit] NULL,
	[MinimumAmount] [float] NULL,
	[MaximumAmount] [float] NULL,
	[IsActive] [bit] NULL,
	[CreatedByUserId] [bigint] NULL,
	[CreatedDate] [datetime] NULL,
    [PersonId] INT NULL, 
    CONSTRAINT [PK_SS_Signatories] PRIMARY KEY CLUSTERED ([SignatoryId] ASC),
	CONSTRAINT [FK_SS_Signatories_SS_Person] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[UM_Person] (PersonId),
	CONSTRAINT [FK_SS_Signatories_SS_Reference_Signatory_Designation] FOREIGN KEY ([SignatoryDesignationId]) REFERENCES [dbo].[SS_ReferenceTable] (ReferenceTableId),
	CONSTRAINT [FK_SS_Signatories_SS_Reference_Signatory_Office] FOREIGN KEY ([SignatoryDesignationId]) REFERENCES [dbo].[SS_ReferenceTable] (ReferenceTableId),
	CONSTRAINT [FK_SS_Signatories_SS_Reference_Report_Section] FOREIGN KEY ([ReportSectionId]) REFERENCES [dbo].[SS_ReferenceTable] (ReferenceTableId),
);
